variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""

#image: harbor.corp.local/library/docker:19.03.1

#services:
#  - harbor.corp.local/library/docker:19.03.1-dind

cache:
  paths:
    - .m2/repository/
    - target/
    
stages:
  - build
  - package
  
.maven-build:
  stage: build
  image: maven:latest
  script:
    - mvn compile package

build:
  stage: package
  image: harbor.corp.local/library/docker:19.03.0
  services:
  - harbor.corp.local/library/docker:19.03.0-dind
  script: 
  - docker info
  - docker build -t harbor.corp.local/library/qrcode .
  - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" "${CI_REGISTRY}" --password-stdin
  - docker push harbor.corp.local/library/qrcode
